### ISSUE TITLE
I want to know where is the v2 client

### ISSUE THREAD

**Issue by tamago-cn** [dgraph-io/dgo#104]
`
package dgo

import (
	"context"
	"fmt"
	"math/rand"
	"strings"
	"sync"

	"github.com/dgraph-io/dgo/v2/protos/api"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)
`
It seems that only v2 client can support operations on dgraph v1.1.*, but I find no v2 client under dgo directory

**Comment by jgoodall** [comment]
This works for us:

```
import (
	dgo "github.com/dgraph-io/dgo/v2"
	dgoapi "github.com/dgraph-io/dgo/v2/protos/api"
)
```

with this in our `go.mod`:

```
github.com/dgraph-io/dgo/v2 v2.1.0
```

**Comment by tamago-cn** [comment]
It works, thanks!

**Comment by ylockson** [comment]
I'm having the same issue importing DGO client. I performed a search and found several go.mod files.
   /usr/lib/go-1.13/misc/go.mod 
   /usr/lib/go-1.13/src/go.mod
   /usr/lib/go-1.13/src/cmd/go.mod
   /usr/lib/go-1.13/src/cmd/go/testdata/badmod/go.mod
   /usr/lib/go-1.13/src/cmd/go/testdata/modlegacy/src/new/go.mod  
   /usr/lib/go-1.13/src/cmd/go/testdata/modlegacy/src/new/sub/go.mod
   /usr/lib/go-1.13/src/cmd/go/testdata/modlegacy/src/new/sub/inner/go.mod
   /usr/lib/go-1.13/test/bench/go1/go.mod

In which one(s) should I include the line:
   github.com/dgraph-io/dgo/v2 v2.1.0

Thanks for advising.

> It works, thanks!
