### ISSUE TITLE
v2 Documentation for getting Schema in api.Response

### ISSUE THREAD

**Issue by wildan2711** [dgraph-io/dgo#111]
I've been going through old code, updating it to dgo v2, and I found out that `api.Response` does not have a `Schema` field anymore for schema queries. 

In the [README](https://github.com/dgraph-io/dgo#running-a-query), it still indicates to get the `Schema` field from `api.Response`, while this [PR](https://github.com/dgraph-io/dgo/pull/43/files) seems to get the schema from the `Json` field.

Should the documentation be updated?

**Comment by mangalaman93** [comment]
Thanks for reporting the issue @wildan2711. Raised a PR to fix the documentation.
