### ISSUE TITLE
Backup option in dgo client

### ISSUE THREAD

**Issue by praneelrathore** [dgraph-io/dgo#124]
Will there be a backup option available in dgo client in coming releases. This issue https://github.com/dgraph-io/dgraph/issues/4900 was created sometime ago and it has been accepted. It will be convenient if we can have this api/client for backing up as well. Also, currently what is the recommended way to create backups for the data, for community edition?

**Comment by parasssh** [comment]
This is a reasonable ask. However, note that you will still need to have Enterprise Edition license for backup/restore feature. 

The issue https://github.com/dgraph-io/dgraph/issues/4900 is about making backup/restore available in Community Edition.

**Comment by praneelrathore** [comment]
Thanks @parasssh. I agree for doing backup/restore I would still need the license for enterprise edition. However, for community edition, as mentioned in the issue, it was suggested to use export/import. Can that be also included in dgo, as otherwise I will have to run the GraphQL query on the alpha container itself which is not a good practice for production.

**Comment by parasssh** [comment]
Please open another GitHub issue for it.

**Comment by praneelrathore** [comment]
Apologies. Closed by mistake.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8116). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
