### ISSUE TITLE
Export/Import option in dgo

### ISSUE THREAD

**Issue by praneelrathore** [dgraph-io/dgo#125]
Currently for exporting data, as per the docs [here](https://dgraph.io/docs/deploy/#exporting-database), it is required to run the mentioned GraphQL mutation at the /admin endpoint. This requires either logging in the instance of alpha, or whitelisting some server that can connect to the alpha. This process doesn't seem right when it comes to running Dgraph deployment on production.

It would be really helpful to have export/import client API's, that will take an alpha's address, and run the mentioned mutation on the doc.

**Comment by parasssh** [comment]
It is not specific to `dgo`. 

I believe this is a design discussion that require changes on the dgraph `alpha` server. Can you repost this `dgraph-io/dgraph` repo.
