### ISSUE TITLE
Dgo support for GraphQL queries

### ISSUE THREAD

**Issue by vadavallipavan** [dgraph-io/dgo#126]
Dgraph now supports the standard graphQL queries and mutations , can you please advice the roadmap for dgo client to support the same -how can we use the generated query* , mutate* functions generated

**Comment by parasssh** [comment]
cc: @pawanrawal @MichaelJCompton

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8118). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
