### ISSUE TITLE
Is space and multiple line in a query string essential?

### ISSUE THREAD

**Issue by FlyingOnion** [dgraph-io/dgo#128]
If so, what formats or rules should the string obey?

**Comment by parasssh** [comment]
Can you elaborate? Did you mean query or mutation?

For mutation, the data must be JSON or RDF format. 
For query, it must be GraphQL+- query string described here https://dgraph.io/docs/query-language/ . Specifically, yes, you can omit multiple lines. Spaces are required to tokenize properly. 

e.g.
```
{
  result(func: has(director.film), first: 10) {
    uid
    expand(_all_)
  }
}
```

can also be written as, 
```
{result(func: has(director.film), first: 10) {uid expand(_all_)}}
```
