### ISSUE TITLE
multiple connections and connection pooling

### ISSUE THREAD

**Issue by u007** [dgraph-io/dgo#14]
hi,

does this library support for connection pooling?
do we need to initialise new client connection for every single client request?

how does transaction work? can we reuse the same connection for multiple client?

thank you

**Comment by u007** [comment]
do i use this on main / server,
```
conn, err := grpc.Dial("localhost:9080", grpc.WithInsecure())
if err != nil {
  log.Fatal(err)
}
defer conn.Close()
```

and initiate this client on every handler?
```
dgraphClient := dgo.NewDgraphClient(api.NewDgraphClient(conn))
```

thank you

**Comment by u007** [comment]
guess my answer is answered here:
https://discuss.dgraph.io/t/questions-about-tls/2992/6

**Comment by OrlandoCo** [comment]
@u007 According to this link: [Golang GRPC Repo](https://github.com/grpc/grpc-go/issues/682)

GRPC can safely use a single connection and it's going to be multiplexed, and limited only by the HTTP/2 max concurrent connections.

An according to the graph client in the client.go code you can find the following: 

`// A single client is thread safe for sharing with multiple go routines.
func NewDgraphClient(clients ...api.DgraphClient) *Dgraph {
	dg := &Dgraph{
		dc: clients,
	}

	return dg
}`

So its seems that you can inject the reference of client to every handler, but this can be confirmed by the contributors.

**Comment by u007** [comment]
what if in the future, we may have logged in user account, will this effect clients?

**Comment by srfrog** [comment]
The original question is answered. Closing this.
