### ISSUE TITLE
support for go module

### ISSUE THREAD

**Issue by samadadi** [dgraph-io/dgo#15]
Hi, Go v1.11 is already out with support for modules and other projects slowly are adapting themselves with it. Please adopt this project to go modules too. Thank you so much.

**Comment by sirkon** [comment]
Any progress  on this issue?

**Comment by srfrog** [comment]
No it was put on ice until Go support is non-beta.

**Comment by jgoodall** [comment]
@srfrog - I don't understand your comment. Did you mean you are not going to support go modules until go 1.13?

**Comment by srfrog** [comment]
That is correct. I had made a couple of PRs for this, but we decided to wait until most issues are resolved and the feature is officially supported in Go. But I plan to add go mod support to all the repos: dgo, badger and dgraph.
