### ISSUE TITLE
dart grpc client

### ISSUE THREAD

**Issue by gedw99** [dgraph-io/dgo#5]
i want a dart client to use from flutter

so i tried compiling the the clent to Dart. It has a few issues to clear up but looks like it will work.

Is this the plan for other languages too ? I saw a js and a java client and have no idea if the java one uses the go proto for code gen from.

**Comment by manishrjain** [comment]
We have no plans to build a dart client yet. All the clients use the protos generated, but have native implementations of the logic required to make them work.

**Comment by gedw99** [comment]
ah i see. That clears it up then.

thanks. but pity about Dart..

**Comment by katutz** [comment]
https://github.com/katutz/dgraph

https://pub.dartlang.org/packages/dgraph
