### ISSUE TITLE
txn.Discard() doesn't discard a Txn but commits the data

### ISSUE THREAD

**Issue by jostillmanns** [dgraph-io/dgo#63]
Prior to #39 `txn.Discard()` aborted a transaction. Now the data is commited. Maybe I am misunderstanding the API but the behavior did change after #39 was merged. In particular, https://github.com/dgraph-io/dgo/pull/39/files#diff-086d95904066e9938ebbede858e38b20L209 introduced the breaking change.

**Comment by danielmai** [comment]
Wow, this is not good. Thanks for reporting this issue, @jostillmanns. This will be fixed by #64.
