### ISSUE TITLE
Add builder API for queries

### ISSUE THREAD

**Issue by ehsannm** [dgraph-io/dgo#75]
Do you have plan to add a QueryBuilder to dgo or any 3rdparty lib you suggest. I could not find any

**Comment by campoy** [comment]
We do not have it, but we do have plans to add it (once we release dgraph v1.1 in the following weeks)

But you know what, let's use this issue to track the request since I do not see it on this repo!

Thanks for the reminder, @ehsannm

**Comment by 1l0** [comment]
Yeah it's needed to avoid nonsense typo bugs on queries.

**Comment by campoy** [comment]
I'll give this a try for my flight back to SF on Thursday!

**Comment by 1l0** [comment]
https://github.com/mooncamp/dgx

**Comment by Mentioum** [comment]
I'd like to reference this post here -> [Discuss Draph Post](https://discuss.dgraph.io/t/recommended-way-of-generating-triples-in-the-w3c-standard-rdf-n-quad-format-with-variables/5441)

As this is definitely something I was looking for. :+1:

**Comment by JulesMike** [comment]
Hi @campoy. Thanks for the work you are doing @dgraph. 

> I'll give this a try for my flight back to SF on Thursday!

Since you are the assignee for this issue, has there been any progress so far? Thanks

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8107). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
