### ISSUE TITLE
client batch mutation

### ISSUE THREAD

**Issue by tommyliu1114** [dgraph-io/dgo#96]
hi, dgraph offer batch-mutation tool "dgraph live", which is so helpful . so ,i want to know , have  
a plan making tools like that in this go-client-package?

**Comment by mangalaman93** [comment]
Dgraph live loader internally uses `dgo` client for running mutations. Not sure what you mean here, will you provide us with more clear requirements with an example?

**Comment by tommyliu1114** [comment]
ok,i got it . i just want an api ,which can work like Dgraph live loader

**Comment by tommyliu1114** [comment]
hi,i found dgraph live code as you said.Thanks for tips
